[phases.setup]
nixPkgs = [
  'glib',
  'nss',
  'nspr',
  'dbus',
  'atk',
  'at-spi2-atk',
  'cups',
  'expat',
  'pango',
  'cairo',
  'mesa',
  'libdrm',
  'libxkbcommon',
  'alsa-lib',
  'xorg.libX11',
  'xorg.libxcb',
  'xorg.libXcomposite',
  'xorg.libXcursor',
  'xorg.libXdamage',
  'xorg.libXext',
  'xorg.libXfixes',
  'xorg.libXi',
  'xorg.libXrandr',
  'xorg.libXrender',
]
